Last working version of develop branch
plus the update to run-test.sh.template
to exit when the executable program terminates
with a non-zero exit code

diff --git a/tests/run-test.sh.template b/tests/run-test.sh.template
--- a/tests/run-test.sh.template
+++ b/tests/run-test.sh.template
@@ -6,6 +6,8 @@
 set -o nounset
 # Return highest error code in pipe chain
 set -o pipefail
+# Exit on non-zero exit code
+set -o errexit
 
 ## usage message
 usage='usage: run-test.sh [-hHqv] [-e "ext .."] <testName> <res-tolerance> <out-tolerance> [rebuild-with-fieldmap]'
@@ -91,12 +93,13 @@ fi
 zgoubi_exe="@CMAKE_BINARY_DIR@"/zgoubi
 # leading part of testName.res.expected contains the required input
 zgoubi_cmd="$zgoubi_exe -in ${testName}.res.expected"
+$zgoubi_cmd
 # run zgoubi command
-if [ "$quiet" = true ] ; then
-  zgoubi_res=$(eval $zgoubi_cmd)
-else
-  eval $zgoubi_cmd
-fi
+#if [ "$quiet" = true ] ; then
+  #zgoubi_res=$(eval $zgoubi_cmd)
+#else
+  #eval $zgoubi_cmd
+#fi
 
 if [[ ${4:-} == "rebuild-with-field-map" ]]; then
   rm $fieldMapFile
