Change the template run-test.sh to accept an argument -e for other file extensions to be tested.

diff --git a/tests/run-test.sh.template b/tests/run-test.sh.template
--- a/tests/run-test.sh.template
+++ b/tests/run-test.sh.template
@@ -8,10 +8,10 @@ set -o nounset
 set -o pipefail
 
 ## usage message
-usage='usage: zgoubi-test.sh [-ehHqv] <testName> <res-tolerance> <out-tolerance> [rebuild-with-fieldmap]'
+usage='usage: run-test.sh [-hHqv] [-e "ext .."] <testName> <res-tolerance> <out-tolerance> [rebuild-with-fieldmap]'
 usageF=$usage$'\n'
 usageF=$usageF$'Execute a given test for zgoubi.\n'
-#usageF=$usageF$'  -e "ext ..." A quoted list of file extensions.\n'
+usageF=$usageF$'  -e "ext ..." A quoted list of file extensions.\n'
 usageF=$usageF$'  -h   Print a brief help message and exit.\n'
 usageF=$usageF$'  -H   Print this help message and exit.\n'
 usageF=$usageF$'  -q   Suppress  output from zgoubi.\n'
@@ -46,15 +46,17 @@ function link_field_map () {
 }
 
 ## default flags
-quiet=false  # quiet zgoubi
-verb=false   # verbose diffs
+quiet=false      # quiet zgoubi
+verb=false       # verbose diffs
+moreFiles=false  # if more files should be compared
 
 ## initialize the exit status
 xstat=0
 
 ## parse optional arguments
-while getopts "hHqv" opt; do
+while getopts "e:hHqv" opt; do
   case $opt in
+  e) exts=$OPTARG; moreFiles=true;;
   h) echo "$usage"; exit;;
   H) echo "$usageF"; exit;;
   q) quiet=true;;
@@ -77,9 +79,9 @@ testName=$1
 res_error=$2
 out_error=$3
 
-echo " === Test ${testName} for zgoubi. Relative error tolerances: $res_error $out_error ==="
+echo " === Test ${testName} using relative error tolerances: $res_error $out_error ==="
 
-if [[ ${4:-} == "rebuild-with-field-map" ]]; then 
+if [[ ${4:-} == "rebuild-with-field-map" ]]; then
   rebuild_zgoubi
   link_field_map
 fi
@@ -96,7 +98,7 @@ else
   eval $zgoubi_cmd
 fi
 
-if [[ ${4:-} == "rebuild-with-field-map" ]]; then 
+if [[ ${4:-} == "rebuild-with-field-map" ]]; then
   rm $fieldMapFile
 fi
 
@@ -115,18 +117,19 @@ if [ "$stat" -ne 0 ] ; then
 fi
 
 ## compare other files: ${testName}.fe
-exts="SPNPRT.Out"
-for fe in $exts; do
-  result=$(ndiff -relative-error $out_error ${testName}.${fe}.expected zgoubi.${fe})
-  stat=$?
-  if [ "$stat" -ne 0 ] ; then
-    (( ++xstat ))
-    echo "File zgoubi.${fe} differs from ${testName}.${fe}.expected."
-    if [ "$verb" = true ] ; then
-      echo "$result"
+if [ "$moreFiles" = true ] ; then
+  for fe in $exts; do
+    result=$(ndiff -relative-error $out_error ${testName}.${fe}.expected zgoubi.${fe})
+    stat=$?
+    if [ "$stat" -ne 0 ] ; then
+      (( ++xstat ))
+      echo "File zgoubi.${fe} differs from ${testName}.${fe}.expected."
+      if [ "$verb" = true ] ; then
+        echo "$result"
+      fi
     fi
-  fi
-done
+  done
+fi
 
 if [ "$xstat" -eq 0 ]
 then
