Refactor CMake & test workflow
"cmake .." now configures/creates a replacement for an
include file (zgoubi/PARIZ.H).  The newly configured/created
version of the file is placed in the tests/ subdirectory.

Excecuting ctest launches a bash script
(tests/zgoubi-integration-test.sh) that
1. Overwrites zgoubi/PARIZ.H with the version for the corresponding
   test (zgoubi-integration-test).
2. Builds via "make".
3. Executes the test and reports passing or failing.
4. Restores zgoubi/PARIZ.H to its original version.

This commit also replaces warmSnake.map with a compressed version
of same.


Former-commit-id: aaa6e072039e6aaa301c1ba7f114c10ee2de5ff2

diff --git a/tests/zgoubi-integration-test.sh.template b/tests/zgoubi-integration-test.sh.template
--- a/tests/zgoubi-integration-test.sh.template
+++ b/tests/zgoubi-integration-test.sh.template
@@ -7,16 +7,39 @@ set -o nounset
 # Return highest error code in pipe chain
 set -o pipefail
 
+cp "@CMAKE_SOURCE_DIR@"/zgoubi/PARIZ.H original.pariz.h
+pariz_h_file="@ZGOUBI_TEST_BIN_DIR@"/PARIZ.H
+if [[ -f "$pariz_h_file" ]]; then
+  cp "$pariz_h_file" "@CMAKE_SOURCE_DIR@"/zgoubi/
+  make -j
+  mv original.pariz.h "@CMAKE_SOURCE_DIR@"/zgoubi/PARIZ.H 
+else
+  echo "Missing cmake-configured PARIZ.H"
+  exit 1
+fi
+
 cd "@ZGOUBI_TEST_BIN_DIR@"
 if [[ ! -f zgoubi.dat ]]; then
   ln -s centeredHelix_FIT_save_nofinal_150226.res zgoubi.dat
 fi
+export warmSnakeFile=warmSnake.map
+if [[ -f "${warmSnakeFile}.xz" ]]; then
+  xz -dk "${warmSnakeFile}.xz"
+else
+  echo "Missing ${warmSnakeFile}.xz"
+  exit 1
+fi
+
+# Execute zgoubi
 "@CMAKE_BINARY_DIR@"/zgoubi
 
-export num_lines=1147
-if diff <(head -n $num_lines zgoubi.res) <(head -n $num_lines zgoubi.res.expected)
+footer=10
+res_file_length=$(wc -l zgoubi.res.expected | awk '{print $1;}')
+let header=$res_file_length-$footer
+if diff <(head -n $header zgoubi.res) <(head -n $header zgoubi.res.expected)
 then
    echo "Test passed."
 else
    echo "zgoubi.res differs from zgoubi.res.expected"
 fi
+rm $warmSnakeFile
